// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf1RH6Kz67ZDrCkY404dWeGQ44kwSWFAg',
    appId: '1:811218202731:web:69c02ffb0f77a6e97e012e',
    messagingSenderId: '811218202731',
    projectId: 'chat-app-3d237',
    authDomain: 'chat-app-3d237.firebaseapp.com',
    storageBucket: 'chat-app-3d237.appspot.com',
    measurementId: 'G-NXNQWHS9HM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArspEEuKIuBCn0Mb1ah5dFq82AzHSnnos',
    appId: '1:811218202731:android:ce598ac825d6835f7e012e',
    messagingSenderId: '811218202731',
    projectId: 'chat-app-3d237',
    storageBucket: 'chat-app-3d237.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkIdaxsG-YLm8ZZYDves0rX3ltSvB13nY',
    appId: '1:811218202731:ios:038f166e520ed3547e012e',
    messagingSenderId: '811218202731',
    projectId: 'chat-app-3d237',
    storageBucket: 'chat-app-3d237.appspot.com',
    iosBundleId: 'com.example.scholarChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkIdaxsG-YLm8ZZYDves0rX3ltSvB13nY',
    appId: '1:811218202731:ios:038f166e520ed3547e012e',
    messagingSenderId: '811218202731',
    projectId: 'chat-app-3d237',
    storageBucket: 'chat-app-3d237.appspot.com',
    iosBundleId: 'com.example.scholarChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf1RH6Kz67ZDrCkY404dWeGQ44kwSWFAg',
    appId: '1:811218202731:web:dba508f13721d0047e012e',
    messagingSenderId: '811218202731',
    projectId: 'chat-app-3d237',
    authDomain: 'chat-app-3d237.firebaseapp.com',
    storageBucket: 'chat-app-3d237.appspot.com',
    measurementId: 'G-LC9103F978',
  );
}
